language: python
python:
    - 2.7
    - 3.5
    - 3.6
    - pypy
    - pypy3

matrix:
    include:
        - python: "3.7"
          dist: xenial
        - python: "3.8-dev"
          dist: xenial

install:
    - pip install .

script:
    - python setup.py test -q

notifications:
    email: false
